/** Códigos estáveis para erros de validação e operação exibidos pelo desktop. */
export enum AppErrorCode {
  INVALID_OPERATION = 'INVALID_OPERATION',
  MISSING_SOURCE = 'MISSING_SOURCE',
  INVALID_ENVIRONMENT = 'INVALID_ENVIRONMENT',
  ORGANIZATION_REQUIRED = 'ORGANIZATION_REQUIRED',
  ORGANIZATION_NOT_CONFIGURED = 'ORGANIZATION_NOT_CONFIGURED',
  ASSIGNMENTS_REQUIRED = 'ASSIGNMENTS_REQUIRED',
  DUPLICATE_ASSIGNMENT = 'DUPLICATE_ASSIGNMENT',
  NO_VALID_DOCUMENT = 'NO_VALID_DOCUMENT',
  DUPLICATE_XML_PATH = 'DUPLICATE_XML_PATH',
  ASSIGNMENTS_MISMATCH = 'ASSIGNMENTS_MISMATCH',
  COMPANY_REQUIRED_FOR_DOCUMENT = 'COMPANY_REQUIRED_FOR_DOCUMENT',
  COMPANY_NOT_IN_DOCUMENT = 'COMPANY_NOT_IN_DOCUMENT',
  INVALID_INITIAL_COMPANY = 'INVALID_INITIAL_COMPANY',
  BATCH_NOT_FOUND = 'BATCH_NOT_FOUND',
  ACTIVE_COMPANY_NOT_FOUND = 'ACTIVE_COMPANY_NOT_FOUND',
  INVALID_TEXT_FIELD = 'INVALID_TEXT_FIELD',
  DATABASE_NOT_READY = 'DATABASE_NOT_READY',
  INVALID_IPC_INPUT = 'INVALID_IPC_INPUT',
  REQUIRED_FIELD = 'REQUIRED_FIELD',
  INVALID_SOURCE_LIST = 'INVALID_SOURCE_LIST',
  INVALID_SOURCE_KIND = 'INVALID_SOURCE_KIND',
  SOURCE_NOT_APPROVED = 'SOURCE_NOT_APPROVED',
  INVALID_PROGRESS_TOTAL = 'INVALID_PROGRESS_TOTAL',
  INVALID_CNPJ = 'INVALID_CNPJ',
  INVALID_STATE = 'INVALID_STATE',
  INVALID_TIMESTAMP_FORMAT = 'INVALID_TIMESTAMP_FORMAT',
  INVALID_TIMESTAMP_VALUE = 'INVALID_TIMESTAMP_VALUE',
  INVALID_CONTENT_HASH = 'INVALID_CONTENT_HASH',
  DUPLICATE_OCCURRENCE_ID = 'DUPLICATE_OCCURRENCE_ID',
  INVALID_OCCURRENCE_ORDER = 'INVALID_OCCURRENCE_ORDER',
  UNCLASSIFIED_OCCURRENCE = 'UNCLASSIFIED_OCCURRENCE',
  MULTIPLE_ORGANIZATIONS = 'MULTIPLE_ORGANIZATIONS',
  ORGANIZATION_ALREADY_CONFIGURED = 'ORGANIZATION_ALREADY_CONFIGURED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  OCCURRENCE_BATCH_MISMATCH = 'OCCURRENCE_BATCH_MISMATCH',
  DIAGNOSTIC_BATCH_MISMATCH = 'DIAGNOSTIC_BATCH_MISMATCH',
  DOCUMENT_BATCH_MISMATCH = 'DOCUMENT_BATCH_MISMATCH',
  BATCH_CANNOT_CANCEL = 'BATCH_CANNOT_CANCEL',
  BATCH_CANNOT_RESUME = 'BATCH_CANNOT_RESUME',
  INVALID_PACK_VERSION = 'INVALID_PACK_VERSION',
  BATCH_RECORD_NOT_FOUND = 'BATCH_RECORD_NOT_FOUND',
  BATCH_NO_ITEMS = 'BATCH_NO_ITEMS',
  ASSESSMENT_INCOMPLETE = 'ASSESSMENT_INCOMPLETE',
  ASSESSMENT_ITEM_INVALID = 'ASSESSMENT_ITEM_INVALID',
  ASSESSMENT_RUN_MISMATCH = 'ASSESSMENT_RUN_MISMATCH',
  ASSESSMENT_RUN_NOT_FOUND = 'ASSESSMENT_RUN_NOT_FOUND',
  INVALID_OCCURRENCE_SIZE = 'INVALID_OCCURRENCE_SIZE',
  INVALID_STORED_OCCURRENCE_ORDER = 'INVALID_STORED_OCCURRENCE_ORDER',
  INVALID_ACCESS_KEY = 'INVALID_ACCESS_KEY',
  INVALID_DATE = 'INVALID_DATE',
  INVALID_VALIDITY_RANGE = 'INVALID_VALIDITY_RANGE',
  PROFILE_COMPANY_MISMATCH = 'PROFILE_COMPANY_MISMATCH',
  LINKED_PRODUCT_NOT_FOUND = 'LINKED_PRODUCT_NOT_FOUND',
  INVALID_MIGRATION_VERSION_POSITIVE = 'INVALID_MIGRATION_VERSION_POSITIVE',
  INVALID_MIGRATION_VERSION = 'INVALID_MIGRATION_VERSION',
  DUPLICATE_MIGRATION_VERSION = 'DUPLICATE_MIGRATION_VERSION',
  DUPLICATE_MIGRATION_NAME = 'DUPLICATE_MIGRATION_NAME',
  MIGRATION_SEQUENCE_GAP = 'MIGRATION_SEQUENCE_GAP',
  INVALID_MIGRATION_CHECKSUM = 'INVALID_MIGRATION_CHECKSUM',
  MIGRATION_TRANSACTION_CONTROL = 'MIGRATION_TRANSACTION_CONTROL',
  INVALID_MIGRATION_FILENAME = 'INVALID_MIGRATION_FILENAME',
  INVALID_MIGRATION_FILENAME_FORMAT = 'INVALID_MIGRATION_FILENAME_FORMAT',
  APPLIED_MIGRATION_MISSING = 'APPLIED_MIGRATION_MISSING',
  APPLIED_MIGRATION_CHANGED = 'APPLIED_MIGRATION_CHANGED',
  INVALID_SQLITE_TIMEOUT = 'INVALID_SQLITE_TIMEOUT',
  FOREIGN_KEYS_DISABLED = 'FOREIGN_KEYS_DISABLED',
  NESTED_TRANSACTION = 'NESTED_TRANSACTION',
  MEMORY_BACKUP_UNSUPPORTED = 'MEMORY_BACKUP_UNSUPPORTED',
  BACKUP_SAME_PATH = 'BACKUP_SAME_PATH',
  BACKUP_DEST_EXISTS = 'BACKUP_DEST_EXISTS',
  BACKUP_INTEGRITY_FAILED = 'BACKUP_INTEGRITY_FAILED',
  SQLITE_CONNECTION_CLOSED = 'SQLITE_CONNECTION_CLOSED',
  INVALID_INVENTORY_PATH = 'INVALID_INVENTORY_PATH',
  INVENTORY_SOURCE_NOT_FILE = 'INVENTORY_SOURCE_NOT_FILE',
  INVENTORY_SOURCE_CHANGED = 'INVENTORY_SOURCE_CHANGED',
  MAIN_SCHEMA_MISSING = 'MAIN_SCHEMA_MISSING',
  INVALID_XML_LIMIT = 'INVALID_XML_LIMIT',
  INVALID_ZIP_LIMIT = 'INVALID_ZIP_LIMIT',
  IMPORT_CANCELLED = 'IMPORT_CANCELLED',
  ZIP_READ_CANCELLED = 'ZIP_READ_CANCELLED',
  INVALID_REGISTRATION_REVISION = 'INVALID_REGISTRATION_REVISION',
  REGISTRATION_REVISION_CONFLICT = 'REGISTRATION_REVISION_CONFLICT',
  REGISTRATION_NOT_FOUND = 'REGISTRATION_NOT_FOUND',
  REGISTRATION_INACTIVE = 'REGISTRATION_INACTIVE',
  RULE_NOT_FOUND = 'RULE_NOT_FOUND',
  RULE_NOT_DRAFT = 'RULE_NOT_DRAFT',
  RULE_NOT_APPROVED = 'RULE_NOT_APPROVED',
  RULE_DRAFT_EXISTS = 'RULE_DRAFT_EXISTS',
  RULE_INVALID_LEVEL = 'RULE_INVALID_LEVEL',
  RULE_INVALID_CONDITIONS = 'RULE_INVALID_CONDITIONS',
  RULE_INVALID_PRIORITY = 'RULE_INVALID_PRIORITY',
  RULE_APPROVAL_INCOMPLETE = 'RULE_APPROVAL_INCOMPLETE',
  PROFILE_SUGGESTION_STALE = 'PROFILE_SUGGESTION_STALE',
  CALCULATION_RUN_INCOMPLETE = 'CALCULATION_RUN_INCOMPLETE',
  DUPLICATE_CALCULATION_ITEM = 'DUPLICATE_CALCULATION_ITEM',
  CALCULATION_REQUEST_CONFLICT = 'CALCULATION_REQUEST_CONFLICT',
  CALCULATION_DOCUMENT_MISMATCH = 'CALCULATION_DOCUMENT_MISMATCH',
  CALCULATION_PREVIOUS_RUN_MISMATCH = 'CALCULATION_PREVIOUS_RUN_MISMATCH',
  CALCULATION_MEMORY_INCONSISTENT = 'CALCULATION_MEMORY_INCONSISTENT',
}

type ErrorParams = Readonly<Record<string, string | number>>

/** Textos visíveis ao usuário; campos entre chaves recebem parâmetros do erro. */
export enum AppErrorMessage {
  UNKNOWN_FAILURE = 'Falha desconhecida.',
  DATABASE_OPEN_TITLE = 'Não foi possível abrir o banco de dados',
  INVALID_OPERATION = 'Operação de importação inválida ou duplicada.',
  MISSING_SOURCE = 'Selecione ao menos um arquivo.',
  INVALID_ENVIRONMENT = 'Confirme se o lote é de produção ou homologação.',
  ORGANIZATION_REQUIRED = 'Configure o escritório antes de {action}.',
  ORGANIZATION_NOT_CONFIGURED = 'Configure a organização antes de renomeá-la.',
  ASSIGNMENTS_REQUIRED = 'Associe uma empresa a cada nota.',
  DUPLICATE_ASSIGNMENT = 'Há associações duplicadas para uma nota.',
  NO_VALID_DOCUMENT = 'Nenhuma nota fiscal válida foi encontrada nos arquivos.',
  DUPLICATE_XML_PATH = 'Há caminhos de XML duplicados nos arquivos selecionados.',
  ASSIGNMENTS_MISMATCH = 'A seleção de empresas não corresponde às notas. Inspecione os arquivos novamente.',
  COMPANY_REQUIRED_FOR_DOCUMENT = 'Cadastre e selecione uma empresa para {path}.',
  COMPANY_NOT_IN_DOCUMENT = 'O CNPJ da empresa escolhida não consta na nota {path}.',
  INVALID_INITIAL_COMPANY = 'Empresa inicial inválida para o lote.',
  BATCH_NOT_FOUND = 'Lote não encontrado nesta instalação.',
  ACTIVE_COMPANY_NOT_FOUND = 'Empresa ativa não encontrada nesta instalação.',
  INVALID_TEXT_FIELD = 'Campo de texto inválido.',
  DATABASE_NOT_READY = 'Banco de dados ainda não está disponível.',
  INVALID_IPC_INPUT = 'Entrada inválida.',
  REQUIRED_FIELD = '{field} deve ser informado.',
  INVALID_SOURCE_LIST = 'Lista de arquivos inválida.',
  INVALID_SOURCE_KIND = 'Tipo de arquivo inválido.',
  SOURCE_NOT_APPROVED = 'Arquivo não autorizado pelo seletor.',
  INVALID_PROGRESS_TOTAL = 'Total de entradas inválido.',
  INVALID_CNPJ = 'CNPJ inválido.',
  INVALID_STATE = 'UF inválida: {value}.',
  INVALID_TIMESTAMP_FORMAT = '{field} deve usar UTC no formato ISO 8601 canônico.',
  INVALID_TIMESTAMP_VALUE = '{field} contém uma data inválida.',
  INVALID_CONTENT_HASH = 'contentHash deve ser um SHA-256 hexadecimal com 64 caracteres.',
  DUPLICATE_OCCURRENCE_ID = 'occurrenceId repetido no classificador: {id}.',
  INVALID_OCCURRENCE_ORDER = 'order inválida para a ocorrência {id}.',
  UNCLASSIFIED_OCCURRENCE = 'Ocorrência não classificada: {id}.',
  MULTIPLE_ORGANIZATIONS = 'A instalação local possui mais de uma organização.',
  ORGANIZATION_ALREADY_CONFIGURED = 'A organização desta instalação já foi configurada.',
  ORGANIZATION_NOT_FOUND = 'Organização não encontrada.',
  OCCURRENCE_BATCH_MISMATCH = 'Todas as ocorrências devem pertencer ao lote criado.',
  DIAGNOSTIC_BATCH_MISMATCH = 'Todos os diagnósticos devem pertencer ao lote criado.',
  DOCUMENT_BATCH_MISMATCH = 'Todos os documentos devem pertencer ao lote criado.',
  BATCH_CANNOT_CANCEL = 'Lote inexistente ou em estado que não permite cancelamento.',
  BATCH_CANNOT_RESUME = 'Lote inexistente ou em estado que não permite retomada.',
  INVALID_PACK_VERSION = 'Versão do pacote inválida.',
  BATCH_RECORD_NOT_FOUND = 'Lote não encontrado.',
  BATCH_NO_ITEMS = 'O lote não possui itens para reavaliar.',
  ASSESSMENT_INCOMPLETE = 'A reavaliação deve incluir todos os itens do lote.',
  ASSESSMENT_ITEM_INVALID = 'Item inválido ou repetido na reavaliação.',
  ASSESSMENT_RUN_MISMATCH = 'A avaliação do item não corresponde à execução.',
  ASSESSMENT_RUN_NOT_FOUND = 'Execução de avaliação não encontrada neste lote.',
  INVALID_OCCURRENCE_SIZE = 'occurrence.sizeBytes deve ser um inteiro não negativo.',
  INVALID_STORED_OCCURRENCE_ORDER = 'occurrence.order deve ser um inteiro positivo.',
  INVALID_ACCESS_KEY = 'occurrence.accessKey deve possuir 44 dígitos.',
  INVALID_DATE = '{field} deve ser uma data válida no formato AAAA-MM-DD.',
  INVALID_VALIDITY_RANGE = 'Fim da vigência não pode ser anterior ao início.',
  PROFILE_COMPANY_MISMATCH = 'Perfil fiscal inexistente, inativo ou não pertence à empresa selecionada.',
  LINKED_PRODUCT_NOT_FOUND = 'Não foi possível consultar o produto vinculado.',
  INVALID_MIGRATION_VERSION_POSITIVE = 'A versão da migration deve ser um inteiro positivo.',
  INVALID_MIGRATION_VERSION = 'Versão inválida na migration {file}.',
  DUPLICATE_MIGRATION_VERSION = 'Versão de migration duplicada: {version}.',
  DUPLICATE_MIGRATION_NAME = 'Nome de migration duplicado: {name}.',
  MIGRATION_SEQUENCE_GAP = 'Sequência de migrations inválida: esperada versão {expected}, encontrada {actual}.',
  INVALID_MIGRATION_CHECKSUM = 'Checksum inválido na migration {file}.',
  MIGRATION_TRANSACTION_CONTROL = 'A migration {file} contém controle de transação; o executor controla BEGIN e COMMIT.',
  INVALID_MIGRATION_FILENAME = 'Nome de migration inválido: {file}.',
  INVALID_MIGRATION_FILENAME_FORMAT = 'Nome de migration inválido: {file}. Use o formato 0001_nome.sql.',
  APPLIED_MIGRATION_MISSING = 'A migration aplicada {version} ({name}) não existe nesta versão do aplicativo.',
  APPLIED_MIGRATION_CHANGED = 'A migration aplicada {version} ({name}) foi alterada.',
  INVALID_SQLITE_TIMEOUT = 'timeoutMilliseconds deve ser um inteiro não negativo.',
  FOREIGN_KEYS_DISABLED = 'Não foi possível habilitar as chaves estrangeiras do SQLite.',
  NESTED_TRANSACTION = 'Transações aninhadas não são permitidas.',
  MEMORY_BACKUP_UNSUPPORTED = 'Banco em memória não pode gerar backup persistente.',
  BACKUP_SAME_PATH = 'O backup não pode sobrescrever o banco de origem.',
  BACKUP_DEST_EXISTS = 'O destino do backup já existe e não será sobrescrito.',
  BACKUP_INTEGRITY_FAILED = 'O backup SQLite criado não passou na verificação de integridade.',
  SQLITE_CONNECTION_CLOSED = 'A conexão SQLite está fechada.',
  INVALID_INVENTORY_PATH = 'Caminho relativo inválido para inventário: {path}.',
  INVENTORY_SOURCE_NOT_FILE = 'A origem não é um arquivo: {path}.',
  INVENTORY_SOURCE_CHANGED = 'O arquivo foi alterado durante o inventário: {path}.',
  MAIN_SCHEMA_MISSING = 'Schema principal não encontrado: {name}.',
  INVALID_XML_LIMIT = 'Limite XML inválido em {name}: {value}.',
  INVALID_ZIP_LIMIT = 'Limite ZIP inválido em {name}: {value}.',
  IMPORT_CANCELLED = 'Importação cancelada.',
  ZIP_READ_CANCELLED = 'Leitura do ZIP cancelada.',
  INVALID_REGISTRATION_REVISION = 'Revisão do cadastro inválida.',
  REGISTRATION_REVISION_CONFLICT = 'Este cadastro foi alterado em outra operação. Recarregue os dados antes de salvar.',
  REGISTRATION_NOT_FOUND = 'Cadastro não encontrado.',
  REGISTRATION_INACTIVE = 'Este cadastro está inativo. Reative-o antes de alterar o vínculo.',
  RULE_NOT_FOUND = 'Regra fiscal não encontrada.',
  RULE_NOT_DRAFT = 'Somente um rascunho pode ser editado ou aprovado.',
  RULE_NOT_APPROVED = 'Somente uma regra aprovada pode ser revogada ou gerar nova versão.',
  RULE_DRAFT_EXISTS = 'Esta regra já possui um rascunho de nova versão.',
  RULE_INVALID_LEVEL = 'Nível da regra fiscal inválido.',
  RULE_INVALID_CONDITIONS = 'Condições da regra fiscal inválidas ou incompletas para o nível escolhido.',
  RULE_INVALID_PRIORITY = 'Prioridade manual inválida ou sem justificativa.',
  RULE_APPROVAL_INCOMPLETE = 'Informe fundamento legal, vigência e condições antes de aprovar a regra.',
  PROFILE_SUGGESTION_STALE = 'Esta sugestão mudou ou já foi aplicada. Atualize a lista e tente novamente.',
  CALCULATION_RUN_INCOMPLETE = 'Execução de cálculo incompleta.',
  DUPLICATE_CALCULATION_ITEM = 'Número de item repetido na execução de cálculo.',
  CALCULATION_REQUEST_CONFLICT = 'Solicitação de cálculo reutilizada com conteúdo diferente.',
  CALCULATION_DOCUMENT_MISMATCH = 'Documento não pertence ao lote informado.',
  CALCULATION_PREVIOUS_RUN_MISMATCH = 'Execução anterior não pertence ao documento.',
  CALCULATION_MEMORY_INCONSISTENT = 'Memória de cálculo inconsistente.',
}

const errorMessageByCode: Record<AppErrorCode, AppErrorMessage> = {
  [AppErrorCode.INVALID_OPERATION]: AppErrorMessage.INVALID_OPERATION,
  [AppErrorCode.MISSING_SOURCE]: AppErrorMessage.MISSING_SOURCE,
  [AppErrorCode.INVALID_ENVIRONMENT]: AppErrorMessage.INVALID_ENVIRONMENT,
  [AppErrorCode.ORGANIZATION_REQUIRED]: AppErrorMessage.ORGANIZATION_REQUIRED,
  [AppErrorCode.ORGANIZATION_NOT_CONFIGURED]: AppErrorMessage.ORGANIZATION_NOT_CONFIGURED,
  [AppErrorCode.ASSIGNMENTS_REQUIRED]: AppErrorMessage.ASSIGNMENTS_REQUIRED,
  [AppErrorCode.DUPLICATE_ASSIGNMENT]: AppErrorMessage.DUPLICATE_ASSIGNMENT,
  [AppErrorCode.NO_VALID_DOCUMENT]: AppErrorMessage.NO_VALID_DOCUMENT,
  [AppErrorCode.DUPLICATE_XML_PATH]: AppErrorMessage.DUPLICATE_XML_PATH,
  [AppErrorCode.ASSIGNMENTS_MISMATCH]: AppErrorMessage.ASSIGNMENTS_MISMATCH,
  [AppErrorCode.COMPANY_REQUIRED_FOR_DOCUMENT]: AppErrorMessage.COMPANY_REQUIRED_FOR_DOCUMENT,
  [AppErrorCode.COMPANY_NOT_IN_DOCUMENT]: AppErrorMessage.COMPANY_NOT_IN_DOCUMENT,
  [AppErrorCode.INVALID_INITIAL_COMPANY]: AppErrorMessage.INVALID_INITIAL_COMPANY,
  [AppErrorCode.BATCH_NOT_FOUND]: AppErrorMessage.BATCH_NOT_FOUND,
  [AppErrorCode.ACTIVE_COMPANY_NOT_FOUND]: AppErrorMessage.ACTIVE_COMPANY_NOT_FOUND,
  [AppErrorCode.INVALID_TEXT_FIELD]: AppErrorMessage.INVALID_TEXT_FIELD,
  [AppErrorCode.DATABASE_NOT_READY]: AppErrorMessage.DATABASE_NOT_READY,
  [AppErrorCode.INVALID_IPC_INPUT]: AppErrorMessage.INVALID_IPC_INPUT,
  [AppErrorCode.REQUIRED_FIELD]: AppErrorMessage.REQUIRED_FIELD,
  [AppErrorCode.INVALID_SOURCE_LIST]: AppErrorMessage.INVALID_SOURCE_LIST,
  [AppErrorCode.INVALID_SOURCE_KIND]: AppErrorMessage.INVALID_SOURCE_KIND,
  [AppErrorCode.SOURCE_NOT_APPROVED]: AppErrorMessage.SOURCE_NOT_APPROVED,
  [AppErrorCode.INVALID_PROGRESS_TOTAL]: AppErrorMessage.INVALID_PROGRESS_TOTAL,
  [AppErrorCode.INVALID_CNPJ]: AppErrorMessage.INVALID_CNPJ,
  [AppErrorCode.INVALID_STATE]: AppErrorMessage.INVALID_STATE,
  [AppErrorCode.INVALID_TIMESTAMP_FORMAT]: AppErrorMessage.INVALID_TIMESTAMP_FORMAT,
  [AppErrorCode.INVALID_TIMESTAMP_VALUE]: AppErrorMessage.INVALID_TIMESTAMP_VALUE,
  [AppErrorCode.INVALID_CONTENT_HASH]: AppErrorMessage.INVALID_CONTENT_HASH,
  [AppErrorCode.DUPLICATE_OCCURRENCE_ID]: AppErrorMessage.DUPLICATE_OCCURRENCE_ID,
  [AppErrorCode.INVALID_OCCURRENCE_ORDER]: AppErrorMessage.INVALID_OCCURRENCE_ORDER,
  [AppErrorCode.UNCLASSIFIED_OCCURRENCE]: AppErrorMessage.UNCLASSIFIED_OCCURRENCE,
  [AppErrorCode.MULTIPLE_ORGANIZATIONS]: AppErrorMessage.MULTIPLE_ORGANIZATIONS,
  [AppErrorCode.ORGANIZATION_ALREADY_CONFIGURED]: AppErrorMessage.ORGANIZATION_ALREADY_CONFIGURED,
  [AppErrorCode.ORGANIZATION_NOT_FOUND]: AppErrorMessage.ORGANIZATION_NOT_FOUND,
  [AppErrorCode.OCCURRENCE_BATCH_MISMATCH]: AppErrorMessage.OCCURRENCE_BATCH_MISMATCH,
  [AppErrorCode.DIAGNOSTIC_BATCH_MISMATCH]: AppErrorMessage.DIAGNOSTIC_BATCH_MISMATCH,
  [AppErrorCode.DOCUMENT_BATCH_MISMATCH]: AppErrorMessage.DOCUMENT_BATCH_MISMATCH,
  [AppErrorCode.BATCH_CANNOT_CANCEL]: AppErrorMessage.BATCH_CANNOT_CANCEL,
  [AppErrorCode.BATCH_CANNOT_RESUME]: AppErrorMessage.BATCH_CANNOT_RESUME,
  [AppErrorCode.INVALID_PACK_VERSION]: AppErrorMessage.INVALID_PACK_VERSION,
  [AppErrorCode.BATCH_RECORD_NOT_FOUND]: AppErrorMessage.BATCH_RECORD_NOT_FOUND,
  [AppErrorCode.BATCH_NO_ITEMS]: AppErrorMessage.BATCH_NO_ITEMS,
  [AppErrorCode.ASSESSMENT_INCOMPLETE]: AppErrorMessage.ASSESSMENT_INCOMPLETE,
  [AppErrorCode.ASSESSMENT_ITEM_INVALID]: AppErrorMessage.ASSESSMENT_ITEM_INVALID,
  [AppErrorCode.ASSESSMENT_RUN_MISMATCH]: AppErrorMessage.ASSESSMENT_RUN_MISMATCH,
  [AppErrorCode.ASSESSMENT_RUN_NOT_FOUND]: AppErrorMessage.ASSESSMENT_RUN_NOT_FOUND,
  [AppErrorCode.INVALID_OCCURRENCE_SIZE]: AppErrorMessage.INVALID_OCCURRENCE_SIZE,
  [AppErrorCode.INVALID_STORED_OCCURRENCE_ORDER]: AppErrorMessage.INVALID_STORED_OCCURRENCE_ORDER,
  [AppErrorCode.INVALID_ACCESS_KEY]: AppErrorMessage.INVALID_ACCESS_KEY,
  [AppErrorCode.INVALID_DATE]: AppErrorMessage.INVALID_DATE,
  [AppErrorCode.INVALID_VALIDITY_RANGE]: AppErrorMessage.INVALID_VALIDITY_RANGE,
  [AppErrorCode.PROFILE_COMPANY_MISMATCH]: AppErrorMessage.PROFILE_COMPANY_MISMATCH,
  [AppErrorCode.LINKED_PRODUCT_NOT_FOUND]: AppErrorMessage.LINKED_PRODUCT_NOT_FOUND,
  [AppErrorCode.INVALID_MIGRATION_VERSION_POSITIVE]: AppErrorMessage.INVALID_MIGRATION_VERSION_POSITIVE,
  [AppErrorCode.INVALID_MIGRATION_VERSION]: AppErrorMessage.INVALID_MIGRATION_VERSION,
  [AppErrorCode.DUPLICATE_MIGRATION_VERSION]: AppErrorMessage.DUPLICATE_MIGRATION_VERSION,
  [AppErrorCode.DUPLICATE_MIGRATION_NAME]: AppErrorMessage.DUPLICATE_MIGRATION_NAME,
  [AppErrorCode.MIGRATION_SEQUENCE_GAP]: AppErrorMessage.MIGRATION_SEQUENCE_GAP,
  [AppErrorCode.INVALID_MIGRATION_CHECKSUM]: AppErrorMessage.INVALID_MIGRATION_CHECKSUM,
  [AppErrorCode.MIGRATION_TRANSACTION_CONTROL]: AppErrorMessage.MIGRATION_TRANSACTION_CONTROL,
  [AppErrorCode.INVALID_MIGRATION_FILENAME]: AppErrorMessage.INVALID_MIGRATION_FILENAME,
  [AppErrorCode.INVALID_MIGRATION_FILENAME_FORMAT]: AppErrorMessage.INVALID_MIGRATION_FILENAME_FORMAT,
  [AppErrorCode.APPLIED_MIGRATION_MISSING]: AppErrorMessage.APPLIED_MIGRATION_MISSING,
  [AppErrorCode.APPLIED_MIGRATION_CHANGED]: AppErrorMessage.APPLIED_MIGRATION_CHANGED,
  [AppErrorCode.INVALID_SQLITE_TIMEOUT]: AppErrorMessage.INVALID_SQLITE_TIMEOUT,
  [AppErrorCode.FOREIGN_KEYS_DISABLED]: AppErrorMessage.FOREIGN_KEYS_DISABLED,
  [AppErrorCode.NESTED_TRANSACTION]: AppErrorMessage.NESTED_TRANSACTION,
  [AppErrorCode.MEMORY_BACKUP_UNSUPPORTED]: AppErrorMessage.MEMORY_BACKUP_UNSUPPORTED,
  [AppErrorCode.BACKUP_SAME_PATH]: AppErrorMessage.BACKUP_SAME_PATH,
  [AppErrorCode.BACKUP_DEST_EXISTS]: AppErrorMessage.BACKUP_DEST_EXISTS,
  [AppErrorCode.BACKUP_INTEGRITY_FAILED]: AppErrorMessage.BACKUP_INTEGRITY_FAILED,
  [AppErrorCode.SQLITE_CONNECTION_CLOSED]: AppErrorMessage.SQLITE_CONNECTION_CLOSED,
  [AppErrorCode.INVALID_INVENTORY_PATH]: AppErrorMessage.INVALID_INVENTORY_PATH,
  [AppErrorCode.INVENTORY_SOURCE_NOT_FILE]: AppErrorMessage.INVENTORY_SOURCE_NOT_FILE,
  [AppErrorCode.INVENTORY_SOURCE_CHANGED]: AppErrorMessage.INVENTORY_SOURCE_CHANGED,
  [AppErrorCode.MAIN_SCHEMA_MISSING]: AppErrorMessage.MAIN_SCHEMA_MISSING,
  [AppErrorCode.INVALID_XML_LIMIT]: AppErrorMessage.INVALID_XML_LIMIT,
  [AppErrorCode.INVALID_ZIP_LIMIT]: AppErrorMessage.INVALID_ZIP_LIMIT,
  [AppErrorCode.IMPORT_CANCELLED]: AppErrorMessage.IMPORT_CANCELLED,
  [AppErrorCode.ZIP_READ_CANCELLED]: AppErrorMessage.ZIP_READ_CANCELLED,
  [AppErrorCode.INVALID_REGISTRATION_REVISION]: AppErrorMessage.INVALID_REGISTRATION_REVISION,
  [AppErrorCode.REGISTRATION_REVISION_CONFLICT]: AppErrorMessage.REGISTRATION_REVISION_CONFLICT,
  [AppErrorCode.REGISTRATION_NOT_FOUND]: AppErrorMessage.REGISTRATION_NOT_FOUND,
  [AppErrorCode.REGISTRATION_INACTIVE]: AppErrorMessage.REGISTRATION_INACTIVE,
  [AppErrorCode.RULE_NOT_FOUND]: AppErrorMessage.RULE_NOT_FOUND,
  [AppErrorCode.RULE_NOT_DRAFT]: AppErrorMessage.RULE_NOT_DRAFT,
  [AppErrorCode.RULE_NOT_APPROVED]: AppErrorMessage.RULE_NOT_APPROVED,
  [AppErrorCode.RULE_DRAFT_EXISTS]: AppErrorMessage.RULE_DRAFT_EXISTS,
  [AppErrorCode.RULE_INVALID_LEVEL]: AppErrorMessage.RULE_INVALID_LEVEL,
  [AppErrorCode.RULE_INVALID_CONDITIONS]: AppErrorMessage.RULE_INVALID_CONDITIONS,
  [AppErrorCode.RULE_INVALID_PRIORITY]: AppErrorMessage.RULE_INVALID_PRIORITY,
  [AppErrorCode.RULE_APPROVAL_INCOMPLETE]: AppErrorMessage.RULE_APPROVAL_INCOMPLETE,
  [AppErrorCode.PROFILE_SUGGESTION_STALE]: AppErrorMessage.PROFILE_SUGGESTION_STALE,
  [AppErrorCode.CALCULATION_RUN_INCOMPLETE]: AppErrorMessage.CALCULATION_RUN_INCOMPLETE,
  [AppErrorCode.DUPLICATE_CALCULATION_ITEM]: AppErrorMessage.DUPLICATE_CALCULATION_ITEM,
  [AppErrorCode.CALCULATION_REQUEST_CONFLICT]: AppErrorMessage.CALCULATION_REQUEST_CONFLICT,
  [AppErrorCode.CALCULATION_DOCUMENT_MISMATCH]: AppErrorMessage.CALCULATION_DOCUMENT_MISMATCH,
  [AppErrorCode.CALCULATION_PREVIOUS_RUN_MISMATCH]: AppErrorMessage.CALCULATION_PREVIOUS_RUN_MISMATCH,
  [AppErrorCode.CALCULATION_MEMORY_INCONSISTENT]: AppErrorMessage.CALCULATION_MEMORY_INCONSISTENT,
}

function formatAppError(code: AppErrorCode, params: ErrorParams): string {
  return errorMessageByCode[code].replace(/\{(\w+)\}/g, (_, key: string) => String(params[key] ?? `{${key}}`))
}

export class AppError extends Error {
  constructor(readonly code: AppErrorCode, params: ErrorParams = {}) {
    super(formatAppError(code, params))
    this.name = 'AppError'
  }
}

/** Mantém a semântica TypeError para políticas inválidas de XML e ZIP. */
export class AppTypeError extends TypeError {
  constructor(readonly code: AppErrorCode, params: ErrorParams = {}) {
    super(formatAppError(code, params))
    this.name = 'AppTypeError'
  }
}
